### ISSUE TITLE
Easier setup

### ISSUE THREAD

**Issue by hvingelby** [rickybassom/gtk-gist-manager#6]
I found this project, and it looks interesting, but I was not able to try the application out since I get errors when trying to build the vala-gist package in Fedora 27.

Maybe this should be packaged as a flatpak package or something?

**Comment by rickybassom** [comment]
Hi @hvingelby, thank you for your interest in this project.

Please can you send the error log you are getting when installing vala-gist, I'm using Fedora 25 and it seems to be working with me. Can you open an issue in the vala-gist repository with the error log and we can reference it from here.

I plan to look into flatpak in the future once I have fully completed this program.

**Comment by hvingelby** [comment]
Hi @rickybas 

Yes I will open an issue in the vala-gist repo 👍 

It would be very cool if this could be installed through flatpak!
